drop table if exists bookmark cascade
drop table if exists comments cascade
drop table if exists community cascade
drop table if exists company cascade
drop table if exists product cascade
drop table if exists product_image cascade
drop table if exists product_user cascade
drop table if exists questionnaire cascade
drop table if exists ranking cascade
create table bookmark (id bigint generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, product_id bigint, user_id bigint, primary key (id))
create table comments (id bigint generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, comment varchar(255), like_cnt bigint, parents_id bigint, product_id bigint, user_id bigint, primary key (id))
create table community (id bigint generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, contents varchar(255), title varchar(255) not null, view integer, user_id bigint not null, primary key (id))
create table company (id bigint generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, company_description varchar(255), company_name varchar(255), company_number varchar(255), user_id bigint, primary key (id))
create table product (id bigint generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, thumbnail_url varchar(255), vote_cnt bigint, product_description varchar(255), product_name varchar(255), company_id bigint, primary key (id))
create table product_image (id bigint generated by default as identity, url varchar(255), product_id bigint not null, primary key (id))
create table product_user (id bigint generated by default as identity, created_at timestamp(6) not null, updated_at timestamp(6) not null, access_token varchar(255), email varchar(255), nick_name varchar(255), picture varchar(255), sns_type varchar(255), user_name varchar(255), primary key (id))
create table questionnaire (id bigint generated by default as identity, answer varchar(255), answered_at timestamp(6) not null, created_at timestamp(6) not null, question varchar(255) not null, updated_at timestamp(6) not null, user_id bigint not null, primary key (id))
create table ranking (id bigint generated by default as identity, product_id bigint not null, user_id bigint not null, created_at timestamp(6) not null, updated_at timestamp(6) not null, primary key (id))
alter table if exists company add constraint UK_46jubpbtfae2gfb74a3x6qug7 unique (company_name)
alter table if exists product_user add constraint UK_ecwccfnijlcobl3cntv8ll7bn unique (email)
alter table if exists bookmark add constraint FKajkd7pr1np7165dgdtlohad0c foreign key (product_id) references product
alter table if exists bookmark add constraint FKkg68k7ihyl3a54d9avu14bjwy foreign key (user_id) references product_user
alter table if exists comments add constraint FKj9to9e3tjoimlgn3w4vjm4xe3 foreign key (product_id) references product
alter table if exists comments add constraint FKd0asydy8kwqj5f6l6okr43hbl foreign key (user_id) references product_user
alter table if exists community add constraint FKt0uut6b5782tn2adkcy7meoh2 foreign key (user_id) references product_user
alter table if exists company add constraint FKsgw1969061fdsrl9d4hv3ouq1 foreign key (user_id) references product_user
alter table if exists product add constraint FKghawd5rtv8ok565nwpdyyuto9 foreign key (company_id) references company
alter table if exists product_image add constraint FK6oo0cvcdtb6qmwsga468uuukk foreign key (product_id) references product
alter table if exists questionnaire add constraint FK2gjvxnxdbgfotmm8qu76ugl0l foreign key (user_id) references product_user
alter table if exists ranking add constraint FK42qxoovnud5o4r9y6hvrydhiy foreign key (product_id) references product
alter table if exists ranking add constraint FKiidqa19s0ooiavj6sxfc3c1ni foreign key (user_id) references product_user